name: quick_test
version: 0.1.0
description: Quickly test packages
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  dev_build:
  process_run:
  tekartik_pubtest:
    git:
      url: https://github.com/tekartik/pubtest.dart
      ref: dart3a
    version: '>=0.7.1'
