name: quick_test
version: 0.1.0
description: Quickly test packages
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.3'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  pubtest:
    git:
      url: git://github.com/tekartik/pubtest.dart
      ref: dart2
    version: '>=0.2.0'