name: quick_test
version: 0.1.0
description: Quickly test packages
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
    version: '>=0.1.3'
  dev_test:
  tekartik_pubtest:
    git:
      url: git://github.com/tekartik/pubtest.dart
      ref: null_safety
    version: '>=0.7.1'